markdown: kramdown
permalink: /:categories/:year/:title/
paginate: 5
paginate_path: /blog/page:num/
exclude:
  - package.json
  - Gruntfile.js
  - node_modules

defaults:
  -
    scope:
      type: posts
    values:
      layout: blog
      categories: blog

github_avatars:
  desandro: "https://avatars.githubusercontent.com/u/85566?v=3"

gems: [jekyll-paginate]
